### ISSUE TITLE
tasks.due_date and tasks.priority should not be strings

### ISSUE THREAD

**Issue by stejskalleos** [nofaralfasi/todo_list#12]
In [schema.rb](https://github.com/nofaralfasi/todo_list/blob/main/db/schema.rb), `tasks.due_date` and `tasks.priority` are both strings, but I think that `due_date` should be `datetime` and `priority` should be `integer`.

Models should have some validations:
* `due_date` should be validated that it can be only in the future
* `priority` should be limited to some selection, lets say from 1 to 3

UI should be updated accordingly to the changes

**Comment by nofaralfasi** [comment]
Created this [PR](https://github.com/nofaralfasi/todo_list/pull/13) solving this issue.
