### ISSUE TITLE
Add rubocop with github action tests

### ISSUE THREAD

**Issue by Ron-Lavi** [nofaralfasi/todo_list#6]

**Comment by stejskalleos** [comment]
This https://github.com/nofaralfasi/todo_list/issues/7 issue should be done first

**Comment by stejskalleos** [comment]
I think we can skip this task, github actions is something we don't need to care about for now,
there are more important tasks to learn/do.

@Ron-Lavi agree?

**Comment by Ron-Lavi** [comment]
yeah, let's close this one
